### ISSUE TITLE
Ensure the attachment metadata is exposed in the API

### ISSUE THREAD

**Issue by alex-418** [BCcampus/pressbooks#5] opened 2018-07-03 22:17 UTC
https://core.trac.wordpress.org/ticket/38323

https://make.wordpress.org/core/2016/07/20/additional-register_meta-changes-in-4-6/

**Comment by bdolor** [comment] 2018-07-10 22:23
I'm guessing that the reason there is currently no `media` endpoint to the pressbooks extended api is because of the uncertainty that all media in a chapter/front-matter/back-matter/part are uploaded media, some could be remote images/media/attachments for instance. 

**current wp endpoint**
https://opentextbc.ca/geography/wp-json/wp/v2/media/ - lists all media attachments and associated meta

**current wp media meta endpoint**
https://opentextbc.ca/geography/wp-json/wp/v2/media/829 - lists one media attachment with meta

Learned so far: 
- custom attachment metadata shows in the wp endpoint without doing anything except adding custom metadata
- cloning does not currently bring over any image metadata, image title attribute is derived from file name (I'm pretty sure).
- in order to be brought over by the cloning routine, an assumption about uploaded media would have to be made, or
- a new custom endpoint `/pressbooks/v2/chapters/5/attachments/` would list all of the attachments and meta associated with chapter 5 
- image metadata (attributions) would be placed in an appropriate attribute of the `<img>` element that could be easily grabbed by modifying the existing `scrapeAndKneadImages` function  - don't know what this could be, honestly

**Comment by bdolor** [comment] 2018-07-11 19:48
documenting these in the context of looking for the right data structure
* https://core.trac.wordpress.org/ticket/43392
* https://journal.rmccue.io/351/the-complex-state-of-meta-in-the-wordpress-rest-api/
* https://core.trac.wordpress.org/ticket/38323
* https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/

**Comment by bdolor** [comment] 2018-07-12 21:06
decided to move away from storing as an associative array https://github.com/BCcampus/pressbooks/commit/2d6441051ef36a609cae15b83a29520b5eb9b17e

resolved via https://github.com/BCcampus/pressbooks/commit/2fcea753a4971b4c951eabd1d9acc879536e863e

tested at endpoint `https://pressbooks.test/metadata/wp-json/wp/v2/media?parent=18` confirmed that our metadata `pb_attribution_*` is/can be associated with each attachment. 

![image](https://user-images.githubusercontent.com/2048170/42659180-56a3af78-85dc-11e8-829a-bc510ef3ae4e.png)

**Closed as completed** 2018-07-19 21:47 UTC
Labels: MEDIUM - 3
